

name: lear-github-action
on: 
  push:
    branches:
    - 'feature/**'
jobs: 
  security:
    name: security job
    runs-on: ubuntu-latest
    steps:
     - name: Print my username
       run: |
         echo "This formation is called DevOps"
  authentication:
    name: authentication job
    runs-on: ubuntu-latest
    steps:
    - name: Print message
      run: |
        echo "DevOps allows to automate things"