name: Caller Workflow Example

on: 
  push:
    branches:
    - 'ci/**'

jobs:
  call-reusable-workflow:
    permissions:
      content: read
    uses: Sergegouety/cicommon/.github/workflows/reuse.yaml@main
    with:
      channel_id: ${{ vars.CHANNEL_ID }}
    secrets:
      slack_token: ${{ secrets.SLACK_BOT_TOKEN }}


     