name: Caller Workflow Example

on: 
  push:
    branches:
    - 'ci/**'

jobs:
  call-reusable-workflow:
    permissions:
      contents: read
    uses: Sergegouety/cicommon/.github/workflows/reuse.yaml@main
    with:
      channel_id: ${{ vars.CHANNEL_ID }}
      dependency_track_project_name: ${{ vars.PROJECT_NAME }}
    secrets:
      slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
      dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }} 

      
      